[package]
name = "hust"
version = "0.0.3"
edition = "2021"


[dependencies]
tikv-jemallocator = "0.5.0"
clap = { version = "*", features = [
    "derive",
    "suggestions",
    "color",
    "wrap_help",
] }
cidr-utils = "*"
url = "*"
database = { version = "*", path = "crates/database" }

[workspace]
members = ["crates/database"]

[[test]]
name = "first"
path = "tests/first.rs"

[[bin]]
bench = false
path = "crates/core/main.rs"
name = "hust"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
